---
# tasks file for ansible-role-kadula

# - name: Debug hostvars
#   ansible.builtin.debug:
#     var: hostvars['server-10.tme.nebulon.com']

# Install Kadalu tasks
# - name: Check for existing Kadalu plugin
#   ansible.builtin.command:
#     kubectl kadalu version
#   register: kadalu_plugin_check
#   changed_when: false
#   failed_when: kadalu_plugin_check.rc > 1

# - name: Get Kadalu install script
#   ansible.builtin.get_url:
#     url: https://github.com/kadalu/kadalu/releases/latest/download/install.sh
#     dest: "{{ ansible_env.HOME }}"
#     mode: '0744'
#   register: install_script
#   when: kadalu_version not in kadalu_plugin_check.stdout

# - name: Install Kadalu plugin
#   ansible.builtin.command:
#     "{{ install_script.dest }}"
#   changed_when: true
#   when: kadalu_version not in kadalu_plugin_check.stdout

# - name: Install Kadalu operator
#   ansible.builtin.command:
#     kubectl kadalu install
#   changed_when: true
#   when: kadalu_version not in kadalu_plugin_check.stdout

# - name: Wait for Kadalu pods to start


# Configure Kadalu tasks

- name: Copy Kadalu storage pool template
  ansible.builtin.template:
    src: kadalu_storage_pool.j2
    dest: "{{ ansible_env.HOME }}/kadalu_storage_pool.yml"

- name: Copy Kadalu sample app YAML manifest
  ansible.builtin.template:
    src: kadalu_sample_app.j2
    dest: "{{ ansible_env.HOME }}/kadalu_sample_app.yml"

# - name: Apply Kadalu storage pool configuration
#   ansible.builtin.command:
#     kubectl apply -f "{{ ansible_env.HOME }}/kadalu_storage_pool.yml"
#   register: kadalu_sp_result

# - name: Apply Kadalu sample application manifest
#     kubectl apply -f "{{ ansible_env.HOME }}/kadalu_sample_app.yml"
#   register: kadalu_app_result

